// ==============================
// Project coordinates
// ==============================
ThisBuild / version      := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.3.6"

// ==============================
// sbt-antlr4 plugin
// ==============================
// We rely exclusively on the sbt-antlr4 plugin to generate parser/lexer
// sources from src/main/antlr4/sophie.g4. No manual JAR or shelling out.
// Make sure your grammar lives at: src/main/antlr4/sophie.g4
enablePlugins(Antlr4Plugin)

// Tell the plugin which ANTLR tool version to use when generating sources.
// 4.13.2 is the latest stable at the time of writing.
Antlr4 / antlr4Version     := "4.13.2"
// Also generate the Visitor and the Listener APIs alongside the parser.
Antlr4 / antlr4GenVisitor  := true
Antlr4 / antlr4GenListener := true

// ==============================
// Dependencies
// ==============================
// Runtime dependency required by the Java parser/lexer classes generated by ANTLR.
libraryDependencies += "org.antlr" % "antlr4-runtime" % "4.13.2"

// Test stack (ScalaTest for Scala 3.x)
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.19" % Test

libraryDependencies += "com.lihaoyi" %% "upickle" % "3.1.2"

// ==============================
// Notes & How it works
// ==============================
// - Put your grammar at src/main/antlr4/sophie.g4
// - The plugin auto-generates Java sources under:
//     target/scala-<scalaVersion>/src_managed/main
// - The generated sources are compiled together with your Scala code.
// - You do NOT need any custom sbt task or a local antlr-*-complete.jar.
// - To build & run:
//     ;reload ;clean ;compile ;run
//
// If your grammar uses a package header like:
//   @header { package parser; }
// the generated classes will be under that package. Otherwise they will
// use the default package. Prefer setting the package header for clarity.
