// ==============================
// Project coordinates
// ==============================
ThisBuild / version      := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.3.6"

// Default main class for convenience (TUI)
ThisBuild / mainClass := Some("TuiMain")

// ==============================
// sbt-antlr4 plugin
// ==============================
// We rely exclusively on the sbt-antlr4 plugin to generate parser/lexer
// sources from src/main/antlr4/sophie.g4. No manual JAR or shelling out.
// Make sure your grammar lives at: src/main/antlr4/sophie.g4
enablePlugins(Antlr4Plugin)

// Tell the plugin which ANTLR tool version to use when generating sources.
// 4.13.2 is the latest stable at the time of writing.
Antlr4 / antlr4Version     := "4.13.2"
// Also generate the Visitor and the Listener APIs alongside the parser.
Antlr4 / antlr4GenVisitor  := true
Antlr4 / antlr4GenListener := true

// ==============================
// Dependencies
// ==============================
// Runtime dependency required by the Java parser/lexer classes generated by ANTLR.
libraryDependencies += "org.antlr" % "antlr4-runtime" % "4.13.2"

// Test stack (ScalaTest for Scala 3.x)
libraryDependencies += "org.scalatest" %% "scalatest" % "3.2.19" % Test

libraryDependencies += "com.lihaoyi" %% "upickle" % "3.1.2"

// Logging: SLF4J API + Logback implementation
libraryDependencies += "ch.qos.logback" % "logback-classic" % "1.4.11"

// ==============================
// assembly (fat JAR) settings
// ==============================
// sbt-assembly is added in project/plugins.sbt; the snippet below
// configures the generated jar name, the main class and a basic
// merge strategy to avoid common META-INF clashes.
import sbtassembly.AssemblyPlugin.autoImport._
import sbtassembly.{MergeStrategy, PathList}

assembly / assemblyJarName := "sophie-fat.jar"

// Main class: project currently uses top-level object `TuiMain`, so FQN is "TuiMain".
assembly / mainClass := Some("TuiMain")

assembly / assemblyMergeStrategy := {
  case PathList("META-INF", xs @ _*) =>
    xs.map(_.toLowerCase) match {
      case ms if ms.exists(m => m.endsWith(".sf") || m.endsWith(".rsa") || m.endsWith(".dsa")) => MergeStrategy.discard
      case _ => MergeStrategy.first
    }
  case "reference.conf" => MergeStrategy.concat
  case other => MergeStrategy.first
}

// ==============================
// Notes & How it works
// ==============================
// - Put your grammar at src/main/antlr4/sophie.g4
// - The plugin auto-generates Java sources under:
//     target/scala-<scalaVersion>/src_managed/main
// - The generated sources are compiled together with your Scala code.
// - You do NOT need any custom sbt task or a local antlr-*-complete.jar.
// - To build & run:
//     ;reload ;clean ;compile ;run
//
// If your grammar uses a package header like:
//   @header { package parser; }
// the generated classes will be under that package. Otherwise they will
// use the default package. Prefer setting the package header for clarity.

// convenience alias to run the TUI simulation runner without typing the full command
// Usage: in shell: `sbt runTuiSim`  -> executes `runMain RunTuiSim`
// Keep this alias if you want a short way to run the non-interactive simulation runner.
addCommandAlias("runTuiSim", "runMain RunTuiSim")
